// Valida metadatos y genera SQL sin abrir ninguna conexión a PostgreSQL.
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Zuni.Data;
using Zuni.Controllers;
using Zuni.Models.Evaluaciones;
using Zuni.Services;
int checks=0;
void Check(bool ok,string name){if(!ok)throw new Exception(name);checks++;Console.WriteLine("OK: "+name);}
using var db=new ApplicationDbContext(new DbContextOptionsBuilder<ApplicationDbContext>().UseNpgsql("Host=localhost;Database=OfflineChecks;Username=offline").Options);
var assembly=db.GetService<IMigrationsAssembly>();
var ids=assembly.Migrations.Keys.ToArray();
Check(ids.Length==ids.Distinct().Count()&&ids.Count(x=>x=="20261009043711_AddEvaluaciones")==1,"Migraciones únicas; AddEvaluaciones una vez");
Console.WriteLine("MIGRACIONES: "+string.Join(", ",ids));
var initializer=db.GetService<IModelRuntimeInitializer>();
var snapshot=initializer.Initialize(assembly.ModelSnapshot!.Model,designTime:true);
var current=db.GetService<IDesignTimeModel>().Model;
var differ=db.GetService<IMigrationsModelDiffer>();
var differences=differ.GetDifferences(snapshot.GetRelationalModel(),current.GetRelationalModel());
Check(differences.Count==0,"Snapshot coincide exactamente con el modelo combinado");
var migration=assembly.CreateMigration(assembly.Migrations["20261009043711_AddEvaluaciones"],db.Database.ProviderName!);
var target=initializer.Initialize(migration.TargetModel,designTime:true);
var linkMigration=assembly.CreateMigration(assembly.Migrations["20261009060000_AddAsignacionesEstudiantePsicologo"],db.Database.ProviderName!);
var latest=assembly.CreateMigration(assembly.Migrations[assembly.Migrations.Keys.Last()],db.Database.ProviderName!);
var linkTarget=initializer.Initialize(latest.TargetModel,designTime:true);
Check(!differ.HasDifferences(linkTarget.GetRelationalModel(),current.GetRelationalModel()),"TargetModel de última migración coincide con modelo combinado");
var additions=differ.GetDifferences(target.GetRelationalModel(),current.GetRelationalModel());
Check(additions.OfType<CreateTableOperation>().Select(t=>t.Name).Order().SequenceEqual(new[]{"AsignacionesEstudiantePsicologo","ParticipacionesBigFive","AccesosBigFive","DiasAgendaPsicologo","HorariosAgendaPsicologo"}.Order())&&additions.All(op=>op is CreateTableOperation or CreateIndexOperation),"Desde Evaluaciones solo se agregan asignaciones, Big Five, agenda e índices");
Check(linkMigration.UpOperations.OfType<CreateTableOperation>().Select(t=>t.Name).SequenceEqual(new[]{"AsignacionesEstudiantePsicologo"})&&linkMigration.UpOperations.All(op=>op is CreateTableOperation or CreateIndexOperation),"Migración de asignaciones únicamente agrega su tabla e índices");
var migrator=db.GetService<IMigrator>();
var freshSql=migrator.GenerateScript(null,null,MigrationsSqlGenerationOptions.Idempotent);
var upgradeSql=migrator.GenerateScript("20261009043711_AddEvaluaciones",null,MigrationsSqlGenerationOptions.Idempotent);
Check(freshSql.Contains("CREATE TABLE")&&freshSql.Contains("AsignacionesEstudiantePsicologo")&&freshSql.Contains("ResultadosEvaluacion"),"SQL de base nueva incluye ambos módulos");
Check(upgradeSql.Contains("AsignacionesEstudiantePsicologo")&&!upgradeSql.Contains("CREATE TABLE \"Evaluaciones\""),"SQL desde Evaluaciones agrega asignaciones sin recrear Evaluaciones");
var expected=new[]{"Evaluaciones","PreguntasEvaluacion","AsignacionesEvaluacion","RespuestasEvaluacion","ResultadosEvaluacion"};
Check(migration.UpOperations.OfType<CreateTableOperation>().Select(t=>t.Name).Order().SequenceEqual(expected.Order()),"AddEvaluaciones crea solo las cinco tablas previstas");
Check(migration.UpOperations.All(op=>op is CreateTableOperation or CreateIndexOperation),"Up solo agrega tablas/índices; no borra ni altera datos anteriores");
foreach(var table in new[]{"AspNetUsers","AspNetRoles","AspNetUserRoles","PerfilesEstudiante","AuditoriaUsuarios","PasswordResetTokens"}.Concat(expected))Check(current.GetRelationalModel().Tables.Any(t=>t.Name==table),"Modelo conserva "+table);
var assignment=current.FindEntityType(typeof(AsignacionEvaluacion))!;
Check(assignment.FindProperty("Revision")!.IsConcurrencyToken,"Revisión conserva control de concurrencia");
var response=current.FindEntityType(typeof(RespuestaEvaluacion))!;
Check(response.GetForeignKeys().Count(f=>f.Properties.Count==2)==2,"Respuestas mantienen ambas claves foráneas compuestas");
Check(current.GetEntityTypes().Where(e=>e.ClrType.Namespace=="Zuni.Models.Evaluaciones").SelectMany(e=>e.GetForeignKeys()).All(f=>f.DeleteBehavior==DeleteBehavior.Restrict),"Evaluaciones mantienen borrado restringido");
var sql=new EvaluacionesService(db).Consulta("titular-offline").ToQueryString();
Check(sql.Contains("EstudianteId")&&sql.Contains("titular-offline"),"Consulta de Evaluaciones genera SQL filtrado por titular");
var resultSql=db.Set<AsignacionEvaluacion>().Where(a=>a.EstudianteId=="titular-offline"&&a.Estado==EstadoEvaluacion.Finalizada).Select(a=>new{Puntuacion=a.Resultado!=null&&a.Resultado.Publicado?a.Resultado.Puntuacion:null,Observaciones=a.Resultado!=null&&a.Resultado.Publicado?a.Resultado.ObservacionesPublicables:null}).ToQueryString();
Check(resultSql.Contains("CASE")&&resultSql.Contains("Publicado")&&resultSql.Contains("titular-offline"),"SQL de Resultados oculta campos sin autorización y filtra titular");
Check(typeof(EvaluacionesController).GetCustomAttributes(typeof(AuthorizeAttribute),true).Cast<AuthorizeAttribute>().Any(a=>a.Roles=="Estudiante"),"Evaluaciones exige rol Estudiante");
foreach(var method in new[]{"Iniciar","Guardar","Finalizar"})Check(typeof(EvaluacionesController).GetMethod(method)!.IsDefined(typeof(ValidateAntiForgeryTokenAttribute),true),"Antifalsificación en "+method);
Check(new PerfilController().Completar() is RedirectToActionResult{ControllerName:"MiCuenta",ActionName:"Editar"},"Perfil antiguo redirige a MiCuenta sin duplicar edición");
Console.WriteLine($"APROBADAS: {checks} comprobaciones de modelo, migraciones, SQL y rutas. Sin acceso a la base.");
