<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Zuni/Models/CompletarPerfilEstudianteViewModel.cs" Link="CompletarPerfilEstudianteViewModel.cs" />
    <Compile Include="../../Zuni/Models/MiPerfilViewModel.cs" Link="MiPerfilViewModel.cs" />
  </ItemGroup>
</Project>
