// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zuni.Data;

#nullable disable

namespace Zuni.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261009060000_AddAsignacionesEstudiantePsicologo")]
    partial class AddAsignacionesEstudiantePsicologo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Zuni.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DebeCambiarContrasena")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Zuni.Models.AsignacionEstudiantePsicologo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaAsignacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFinalizacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerfilEstudianteId")
                        .HasColumnType("uuid");

                    b.Property<string>("PsicologoUsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerfilEstudianteId")
                        .IsUnique()
                        .HasDatabaseName("UX_AsignacionesEstudiantePsicologo_PerfilEstudiante_Vigente")
                        .HasFilter("\"FechaFinalizacionUtc\" IS NULL");

                    b.HasIndex("PsicologoUsuarioId", "FechaFinalizacionUtc");

                    b.ToTable("AsignacionesEstudiantePsicologo", null, t =>
                        {
                            t.HasCheckConstraint("CK_AsignacionesEstudiantePsicologo_Fechas", "\"FechaFinalizacionUtc\" IS NULL OR \"FechaFinalizacionUtc\" >= \"FechaAsignacionUtc\"");
                        });
                });

            modelBuilder.Entity("Zuni.Models.AuditoriaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AdministradorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("jsonb");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UsuarioAfectadoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("UsuarioAfectadoId");

                    b.ToTable("AuditoriaUsuarios", (string)null);
                });

            modelBuilder.Entity("Zuni.Models.Evaluaciones.AsignacionEvaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Comprobante")
                        .HasColumnType("uuid");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaAsignacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFinalizacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Comprobante")
                        .IsUnique();

                    b.HasIndex("EvaluacionId");

                    b.HasIndex("EstudianteId", "EvaluacionId")
                        .IsUnique();

                    b.ToTable("AsignacionesEvaluacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Asignacion_Estado", "\"Estado\" BETWEEN 0 AND 3");

                            t.HasCheckConstraint("CK_Asignacion_Finalizacion", "(\"Estado\" = 3 AND \"FechaFinalizacionUtc\" IS NOT NULL AND \"Comprobante\" IS NOT NULL AND \"FechaInicioUtc\" IS NOT NULL) OR (\"Estado\" <> 3 AND \"FechaFinalizacionUtc\" IS NULL AND \"Comprobante\" IS NULL)");

                            t.HasCheckConstraint("CK_Asignacion_Inicio", "\"Estado\" <> 2 OR \"FechaInicioUtc\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Zuni.Models.Evaluaciones.Evaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("EsDemostracion")
                        .HasColumnType("boolean");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Evaluaciones", (string)null);
                });

            modelBuilder.Entity("Zuni.Models.Evaluaciones.PreguntaEvaluacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Obligatoria")
                        .HasColumnType("boolean");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluacionId", "Orden")
                        .IsUnique();

                    b.ToTable("PreguntasEvaluacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pregunta_Orden", "\"Orden\" > 0");
                        });
                });

            modelBuilder.Entity("Zuni.Models.Evaluaciones.RespuestaEvaluacion", b =>
                {
                    b.Property<Guid>("AsignacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PreguntaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvaluacionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Valor")
                        .HasColumnType("integer");

                    b.HasKey("AsignacionId", "PreguntaId");

                    b.HasIndex("AsignacionId", "EvaluacionId");

                    b.HasIndex("PreguntaId", "EvaluacionId");

                    b.ToTable("RespuestasEvaluacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Respuesta_Valor", "\"Valor\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Zuni.Models.Evaluaciones.ResultadoEvaluacion", b =>
                {
                    b.Property<Guid>("AsignacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObservacionesPublicables")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("Publicado")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicadoPorId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublicadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Puntuacion")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("AsignacionId");

                    b.HasIndex("PublicadoPorId");

                    b.ToTable("ResultadosEvaluacion", null, t =>
                        {
                            t.HasCheckConstraint("CK_Resultado_Publicacion", "NOT \"Publicado\" OR (\"PublicadoUtc\" IS NOT NULL AND \"PublicadoPorId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Zuni.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAtUtc", "UsedAtUtc");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("Zuni.Models.PerfilEstudiante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Carne")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Carrera")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CicloAcademico")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreContactoEmergencia")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RelacionContactoEmergencia")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Semestre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TelefonoContactoEmergencia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Carne")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilesEstudiante", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Zuni.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Zuni.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zuni.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Zuni.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zuni.Models.AsignacionEstudiantePsicologo", b =>
                {
                    b.HasOne("Zuni.Models.PerfilEstudiante", "PerfilEstudiante")
                        .WithMany()
                        .HasForeignKey("PerfilEstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zuni.Models.ApplicationUser", "PsicologoUsuario")
                        .WithMany()
                        .HasForeignKey("PsicologoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerfilEstudiante");

                    b.Navigation("PsicologoUsuario");
                });

            modelBuilder.Entity("Zuni.Models.Evaluaciones.AsignacionEvaluacion", b =>
                {
                    b.HasOne("Zuni.Models.ApplicationUser", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zuni.Models.Evaluaciones.Evaluacion", "Evaluacion")
                        .WithMany()
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("Zuni.Models.Evaluaciones.PreguntaEvaluacion", b =>
                {
                    b.HasOne("Zuni.Models.Evaluaciones.Evaluacion", "Evaluacion")
                        .WithMany("Preguntas")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("Zuni.Models.Evaluaciones.RespuestaEvaluacion", b =>
                {
                    b.HasOne("Zuni.Models.Evaluaciones.AsignacionEvaluacion", "Asignacion")
                        .WithMany("Respuestas")
                        .HasForeignKey("AsignacionId", "EvaluacionId")
                        .HasPrincipalKey("Id", "EvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zuni.Models.Evaluaciones.PreguntaEvaluacion", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaId", "EvaluacionId")
                        .HasPrincipalKey("Id", "EvaluacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignacion");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("Zuni.Models.Evaluaciones.ResultadoEvaluacion", b =>
                {
                    b.HasOne("Zuni.Models.Evaluaciones.AsignacionEvaluacion", "Asignacion")
                        .WithOne("Resultado")
                        .HasForeignKey("Zuni.Models.Evaluaciones.ResultadoEvaluacion", "AsignacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Zuni.Models.ApplicationUser", "PublicadoPor")
                        .WithMany()
                        .HasForeignKey("PublicadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asignacion");

                    b.Navigation("PublicadoPor");
                });

            modelBuilder.Entity("Zuni.Models.PasswordResetToken", b =>
                {
                    b.HasOne("Zuni.Models.ApplicationUser", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Zuni.Models.PerfilEstudiante", b =>
                {
                    b.HasOne("Zuni.Models.ApplicationUser", "Usuario")
                        .WithOne("PerfilEstudiante")
                        .HasForeignKey("Zuni.Models.PerfilEstudiante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Zuni.Models.ApplicationUser", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("PerfilEstudiante");
                });

            modelBuilder.Entity("Zuni.Models.Evaluaciones.AsignacionEvaluacion", b =>
                {
                    b.Navigation("Respuestas");

                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("Zuni.Models.Evaluaciones.Evaluacion", b =>
                {
                    b.Navigation("Preguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
